#Numpy -> its a multidimensional array librabry .i,e u can store all sort of data.like 1-d,2-d,n-d;
#downloading Numpy(remeber to pip or pip3 install numpy first on terminal)



In [3]:
import numpy as np

In [3]:
#THE BASICS :

#initialize array
a=np.array([1,2,3],dtype="int16") # with assigning to dtype i,e keyword argument we  can make it possible to store our data in specified number of bytes
#but it need to fit into that specified byte of storage; 
print("one dimensional array :",a)

b=np.array([[1.0,2.0,3.0,5.8],[2.1,3,4.2,4.5]])
print("two dimensional array :",b)

one dimensional array : [1 2 3]
two dimensional array : [[1.  2.  3.  5.8]
 [2.1 3.  4.2 4.5]]


In [4]:
#Get Dimension
print("dimension of a :",a.ndim)
print("dimension of b :",b.ndim)

dimension of a : 1
dimension of b : 2


In [5]:
#Get Shape
print("shape of a :",a.shape) #its a vector so its tellings us one dimension 
print("shape of b :",b.shape)


shape of a : (3,)
shape of b : (2, 4)


In [6]:
#Get  Type
print("a type is :",a.dtype)

a type is : int16


In [7]:
#Get Size
print("size of a :",a.size) # # of element in the array.i,e length of array;

size of a : 3


In [8]:
#total size
print("a item size :",a.itemsize) # size of single element in the array .i,e in bytes;
print("total size is a:",a.size*a.itemsize)

a item size : 2
total size is a: 6


In [9]:
#ACCESSING/CHANGING SPECIFIC ELEMENTS,ROWS,COLUMNS ETC

In [10]:
#Get specific element [row,column] -ve index is possible similar to list;
b[1,2]

np.float64(4.2)

In [11]:
#Get specific row [row,:]#we use slicing(:) operation
print("row :",b[1,0:1]);

row : [2.1]


In [12]:
#Get specific column[:,column]
print("column :",b[:,1])

column : [2. 3.]


In [13]:
#Getting a little more fancy [starindex:endindex:steps]
print("subset of specific row",b[1,1::2])


subset of specific row [3.  4.5]


In [14]:
#change element
b[1,2]=8
print(b)

b[:,2]=[9,4]
b

[[1.  2.  3.  5.8]
 [2.1 3.  8.  4.5]]


array([[1. , 2. , 9. , 5.8],
       [2.1, 3. , 4. , 4.5]])

In [1]:
int(1.2)

1

# 3-d Example

In [13]:
c=np.array([[
         [1,2,5],[3,4,5],
          ],
          [
          [5,6,6],[7,8,7]
            ]])

In [22]:
#get specific element (work outside in)
print("specified element is:",c[1,1,2])

specified element is: 7


In [23]:
c[1,1,2] = 100
c

array([[[  1,   2,   5],
        [  3,   4,   5]],

       [[  5,   6,   6],
        [  7,   8, 100]]])

In [14]:
c

array([[[1, 2, 5],
        [3, 4, 5]],

       [[5, 6, 6],
        [7, 8, 7]]])

In [15]:
type(c)

numpy.ndarray

In [16]:
c.ndim

3

In [17]:
c.shape

(2, 2, 3)

In [18]:
c.size

12

## calculate the memory space took for c numpy array

In [19]:
c.dtype

dtype('int64')

In [20]:
c.itemsize * c.size

96

# initilizing differnt type of array

In [4]:
np.zeros((3,4)) #3 rows and 4 coloumns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
zm = np.zeros((3,4)) #3 rows and 4 coloums

In [8]:
zm.ndim

2

In [9]:
zm.shape

(3, 4)

### All 1's Matrix

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.ones((3,3),dtype="int16") #3 rows and 3 coloums

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [13]:
ones = np.ones((3,3),dtype = "int16")

In [15]:
ones[1,1] = 100
ones

array([[  1,   1,   1],
       [  1, 100,   1],
       [  1,   1,   1]], dtype=int16)

#Any other number


In [16]:
np.full(ones.shape,88)

array([[88, 88, 88],
       [88, 88, 88],
       [88, 88, 88]])

In [18]:
np.full((4,5),100 ,dtype = "float")

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [19]:
m100 = np.full((4,5),100,dtype = "float")
m100

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

##### reuse the already existing array and assign one value to 

In [20]:
np.full_like(m100,200,dtype = "float")

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

### Random matrix

In [21]:
np.random.random_sample((2,3))

array([[0.97033867, 0.23600609, 0.46982301],
       [0.11664471, 0.28197772, 0.32843965]])

In [23]:
np.random.rand(2,3)

array([[0.81206671, 0.01656028, 0.15448017],
       [0.07213964, 0.69858334, 0.51419953]])

In [24]:
np.random.randint(6,9,size=(3,3))

array([[6, 8, 6],
       [7, 6, 8],
       [6, 8, 8]], dtype=int32)

#### indentity matrix

In [26]:
np.identity(5)# 5,5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.identity(0)

array([], shape=(0, 0), dtype=float64)